=== AmikDon/Online-Vehicle-Shop-Model/catalog_18029188.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="onlineShop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="shop">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="address" type="xs:string"/>
							<xs:element name="telephone" type="xs:string"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="logo" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="welcome">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="brands">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="Left" type="xs:string" minOccurs="1" maxOccurs="4"/>
										<xs:element name="Right" type="xs:string" minOccurs="1" maxOccurs="4"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="vehicles">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element name="vehicle" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="info">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="itemNo" type="xs:integer"/>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="quantity" type="xs:string"/>
													<xs:element name="price" type="xs:string"/>
													<xs:element name="color" type="xs:string"/>
													<xs:element name="description" type="xs:string"/>
													<xs:element name="image1" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image2" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image3" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image4" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image5" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image6" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image7" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image8" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image9" minOccurs="0" maxOccurs="1"/>
													<xs:element name="image10" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="detailInfo">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="left">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="engineDetail">
																	<xs:complexType mixed="true">
																		<xs:sequence>
																			<xs:element name="fuelType" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="horsePower" type="xs:string"/>
																			<xs:element name="horsePowerRpm" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="torqueRpm" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="ecoMode" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="sportMode" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="aspiration" type="xs:string" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																		<xs:attribute name="type" type="xs:string" use="required"/>
																	</xs:complexType>
																</xs:element>
																<xs:element name="interior">
																	<xs:complexType mixed="true">
																		<xs:sequence>
																			<xs:element name="seatMaterial" type="xs:string"/>
																			<xs:element name="automaticPowerWindows" type="xs:string"/>
																			<xs:element name="frontHeatedSeats" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="rearHeatedSeats" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="frontCooledSeats" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="powerWindows" type="xs:string"/>
																			<xs:element name="powerLocks" type="xs:string"/>
																			<xs:element name="doorTrim" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="interiorTrim" type="xs:string" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																		<xs:attribute name="ambientLighting" type="xs:string" use="optional"/>
																		<xs:attribute name="frontSeatType" type="xs:string" use="required"/>
																		<xs:attribute name="secondRowSeatType" type="xs:string" use="required"/>
																		<xs:attribute name="thirdRowSeatType" type="xs:string" use="optional"/>
																	</xs:complexType>
																</xs:element>
																<xs:element name="exterior">
																	<xs:complexType mixed="true">
																		<xs:sequence>
																			<xs:element name="headLampType" type="xs:string"/>
																			<xs:element name="tailLampType" type="xs:string"/>
																			<xs:element name="fogLamps" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="windshieldWipers" type="xs:string"/>
																			<xs:element name="convertibleRoof" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="roofrails" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="moonRoof" type="xs:string" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																		<xs:attribute name="foldingSideMirrors" type="xs:string" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="right">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="performance">
																	<xs:complexType mixed="true">
																		<xs:sequence>
																			<xs:element name="frontBrakes" type="xs:string"/>
																			<xs:element name="rearBrakes" type="xs:string"/>
																			<xs:element name="stabilizerBar" type="xs:string" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="safety">
																	<xs:complexType mixed="true">
																		<xs:sequence>
																			<xs:element name="brakeAssist" type="xs:string" maxOccurs="1"/>
																			<xs:element name="automaticBraking" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="blindSpotSystem" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="forwardCollisionWarning" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="parkingSensors" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="alarm" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="tractionControl" type="xs:string" maxOccurs="1"/>
																			<xs:element name="stabilityControl" type="xs:string" maxOccurs="1"/>
																			<xs:element name="sideAirBags" type="xs:string" maxOccurs="1"/>
																			<xs:element name="curtainAirBags" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="kneeAirBags" type="xs:string" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="pedestrianDetection" type="xs:string" minOccurs="0" maxOccurs="1"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="footer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="address" type="xs:string"/>
							<xs:element name="telephone" type="xs:string"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="logo" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AmikDon/Online-Vehicle-Shop-Model/catalog_18029188.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_18029188.css"?>
<onlineShop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_18029188.xsd">
	<shop>
		<name>NY Vehicle Shop</name>
		<address>New York</address>
		<telephone>+1 914-969-99999</telephone>
		<email>nyvehicle_shop@gmail.com</email>
		<logo/>
	</shop>

	<welcome> Welcome to NY Vehicle Shop
		<brands> Available Brands
			<Left>Toyota</Left>
			<Left>Mazda</Left>
			<Left>Audi</Left>
			<Left>Ford</Left>
			<Right>BMW</Right>
			<Right>Chrysler</Right>
			<Right>Lexus</Right>
		</brands>
	</welcome>

	<vehicles>
		<vehicle type = "suv">
			<info>
				<itemNo>1</itemNo>
				<name>2020 Toyota Highlander</name>
				<type>Type: SUV</type>
				<quantity>Quantity: 3</quantity>
				<price>Price: $35,720</price>
				<color>Color: Moon Dust, Blizzard Pearl, Magnetic Grey Metallic</color>
				<description>With a fresh redesign for 2020, the Toyota Highlander is one of the strongest competitors in the three-row SUV segment. It has a more stylish exterior and better fuel economy, with more technical features and better cargo capacity. The Highlander has its comfort, refinement, and dependable reputation. With its steady improvements, the Toyota Highlander stays near the front of the pack even with high competitors. The Toyota Highlander is a 7-seater vehicle. The most popular style is the XLE AWD, which comes with a 3.5L V6 engine and All Wheel Drive. This Highlander has 36 MPG in the city and 35 MPG on the highway.</description>
				<image1/>
			</info>
			<detailInfo>
				<left>
					<engineDetail type = "Hybrid"> Engine Details			
						<horsePower>Horsepower: 243 hp</horsePower>
						<horsePowerRpm>Horsepower RPM: 6000 rpm</horsePowerRpm>
						<torqueRpm>Torque RPM: 4400 rpm</torqueRpm>
						<ecoMode>Eco Mode: Included</ecoMode>
						<sportMode>Sport Mode: Included</sportMode>
					</engineDetail>
					<interior ambientLighting = "yes" frontSeatType = "Bucket" secondRowSeatType = "Captain" thirdRowSeatType = "Bench"> Interior
						<seatMaterial>Seat material: Leather</seatMaterial>
						<automaticPowerWindows>Automatic Power Windows: Front and Rear</automaticPowerWindows>
						<frontHeatedSeats>Front Heated Seats: Multi-Level</frontHeatedSeats>
						<rearHeatedSeats>Rear Heated Seats: Multi-Level</rearHeatedSeats>
						<frontCooledSeats>Front Cooled Seats: Multi-Level</frontCooledSeats>
						<powerWindows>Power Windows: Included</powerWindows>
						<powerLocks>Power Locks: Included</powerLocks>
						<doorTrim>Door Trim: Leather and Wood</doorTrim>
						<interiorTrim>Interior Trim: Metal and Wood</interiorTrim>
					</interior>
					<exterior foldingSideMirrors = "Manual"> Exterior
						<headLampType>Head Lamp Type: LED</headLampType>
						<tailLampType>Tail Lamp Type: LED</tailLampType>
						<fogLamps>Fog Lamps: Included</fogLamps>
						<windshieldWipers>Wind Shield Wipers: Rain Sensing</windshieldWipers>
						<roofrails>Roof Rails: Included</roofrails>
					</exterior>
				</left>
				<right>
					<performance> Performance
						<frontBrakes>Front Brakes: Ventilated Disc</frontBrakes>
						<rearBrakes>Rear Brakes: Disc</rearBrakes>
						<stabilizerBar>Stabilizer: Front and Rear</stabilizerBar>
					</performance>
					<safety> Safety
						<brakeAssist>Brake Assist: Included</brakeAssist>
						<automaticBraking>Automatic Braking: Included</automaticBraking>
						<blindSpotSystem>Blind Spot System: Active Warning</blindSpotSystem>
						<forwardCollisionWarning>Forward Collision Warning: Active</forwardCollisionWarning>
						<parkingSensors>Parking Sensors: Front and Rear</parkingSensors>
						<alarm>Alarm: Included</alarm>
						<tractionControl>Traction Control: Included</tractionControl>
						<stabilityControl>Stability Control: Included</stabilityControl>
						<sideAirBags>Side Air Bags: Front</sideAirBags>
						<curtainAirBags>Curtain Air Bags: Front, Rear and 3rd Row</curtainAirBags>
						<kneeAirBags>Knee Air Bags: Included</kneeAirBags>
						<pedestrianDetection>Pedestrian Detection: Included</pedestrianDetection>
					</safety>
				</right>
			</detailInfo>
		</vehicle>
		
		<vehicle type = "sedan">
			<info>
				<itemNo>2</itemNo>
				<name>2020 Mazda Mazda3</name>
				<type>Type: Sedan</type>
				<quantity>Quantity: 2</quantity>
				<price>$22,445</price>
				<color>Color: Red, Black</color>
				<description>The Mazda Mazda3 is a compact car with the soul of a sports car. The Mazda3 is available as a sedan or hatchback. The Mazda3 offers refinement and fuel efficiency. It has driver safety aids like lane-keep assist and adaptive cruise control. It was redesigned in 2019 and is in its fourth generation. It is a 5-seater vehicle that comes in 4 trim levels. The most popular style is the Select Package 4-Door FWD Automatic. It starts at $23,645 and comes with a 2.5L I4 engine and Front Wheel Drive. This Mazda3 has 27 MPG in the city and 36 MPG on the highway.</description>
				<image2/>
			</info>
			<detailInfo>
				<left>
					<engineDetail type = "Gas">	Engine Details
						<fuelType>Fuel Type: Regular Unleaded</fuelType>			
						<horsePower>Horsepower: 186 hp</horsePower>
						<horsePowerRpm>Horsepower RPM: 6000 rpm</horsePowerRpm>
						<torqueRpm>Torque RPM: 4000 rpm</torqueRpm>
						<sportMode>Sport Mode: Included</sportMode>
					</engineDetail>
					<interior frontSeatType = "Sport" secondRowSeatType = "Bench"> Interior
						<seatMaterial>Seat Material: Leather</seatMaterial>
						<automaticPowerWindows>Automatic Power Windows: Front and Rear</automaticPowerWindows>
						<frontHeatedSeats>Front Heated Seats: Multi-Level</frontHeatedSeats>
						<powerWindows>Power Windows: Included</powerWindows>
						<powerLocks>Power Locks: Included</powerLocks>
						<doorTrim>Door Trim: Leatherette</doorTrim>
						<interiorTrim>Interior Trim: Plastic</interiorTrim>
					</interior>
					<exterior foldingSideMirrors = "Manual"> Exterior
						<headLampType>Head Lamp Type: LED</headLampType>
						<tailLampType>Tail Lamp Type: LED</tailLampType>
						<windshieldWipers>Wind Shield Wipers: Rain Sensing</windshieldWipers>
						<moonRoof>Moon Roof: Power</moonRoof>
					</exterior>
				</left>
				<right>
					<performance> Performance
						<frontBrakes>Front Brakes: Ventilated Disc</frontBrakes>
						<rearBrakes>Rear Brakes: Disc</rearBrakes>
						<stabilizerBar>Stabilizer: Front</stabilizerBar>
					</performance>
					<safety> Safety
						<brakeAssist>Brake Assist: Included</brakeAssist>
						<automaticBraking>Automatic Braking: Included</automaticBraking>
						<blindSpotSystem>Blind Spot System: Monitor</blindSpotSystem>
						<forwardCollisionWarning>Forward Collision Warning: Active</forwardCollisionWarning>
						<tractionControl>Traction Control: Included</tractionControl>
						<stabilityControl>Stability Control: Included</stabilityControl>
						<sideAirBags>Side Air Bags: Front</sideAirBags>
						<curtainAirBags>Curtain Air Bags: Front and Rear</curtainAirBags>
						<kneeAirBags>Knee Air Bags: Included</kneeAirBags>
					</safety>
				</right>
			</detailInfo>
		</vehicle>

		<vehicle type = "hatchback">
			<info>
				<itemNo>3</itemNo>
				<name>2020 Toyota Prius Prime</name>
				<type>Type: Hatchback</type>
				<quantity>Quantity: 2</quantity>
				<price>$28,855</price>
				<color>Color: Supersonic Red, Blue Magnetism</color>
				<description>The Toyota Prius Prime is a five-door hybrid vehicle. It is meant for people who want more ways to save fuel. It was debuted in 2017. The Prius Prime is the plug-in version. It allows its battery to be recharged at a charging station or home. It comes with more conventional exterior styling, and more premium interior. The Toyota Prius Prime is a 5-seater vehicle and comes in 3 trim levels. The most popular style is the XLE. It starts at $30,755 and comes with a Plug-In 1.8L I4 engine and Front Wheel Drive. It has 55 MPG in the city and 53 MPG on the highway.</description>
				<image3/>
			</info>
			<detailInfo>
				<left>
					<engineDetail type = "Plug-In"> Engine Details
						<fuelType>Fuel Type: Regular Unleaded</fuelType>			
						<horsePower>Horsepower: 121 hp</horsePower>
						<horsePowerRpm>Horsepower RPM: 5200 rpm</horsePowerRpm>
						<torqueRpm>Torque RPM: 3600 rpm</torqueRpm>
						<ecoMode>Eco Mode: Included</ecoMode>
						<sportMode>Sport Mode: Included</sportMode>
					</engineDetail>
					<interior ambientLighting = "yes" frontSeatType = "Bucket" secondRowSeatType = "Bench"> Interior
						<seatMaterial>Seat material: Leatherette and Cloth</seatMaterial>
						<automaticPowerWindows>Automatic Power Windows: Front and Rear</automaticPowerWindows>
						<frontHeatedSeats>Front Heated Seats: Multi-Level</frontHeatedSeats>
						<powerWindows>Power Windows: Included</powerWindows>
						<powerLocks>Power Locks: Included</powerLocks>
						<doorTrim>Door Trim: Leatherette</doorTrim>
						<interiorTrim>Interior Trim: Plastic</interiorTrim>
					</interior>
					<exterior foldingSideMirrors = "Manual"> Exterior
						<headLampType>Head Lamp Type: LED</headLampType>
						<tailLampType>Tail Lamp Type: LED</tailLampType>
						<fogLamps>Fog Lamps: Included</fogLamps>
						<windshieldWipers>Wind Shield Wipers: Rain Sensing</windshieldWipers>
						<roofrails>Roof Rails: Included</roofrails>
					</exterior>
				</left>
				<right>
					<performance> Performance
						<frontBrakes>Front Brakes: Ventilated Disc</frontBrakes>
						<rearBrakes>Rear Brakes: Disc</rearBrakes>
						<stabilizerBar>Stabilizer: Front and Rear</stabilizerBar>
					</performance>
					<safety> Safety
						<brakeAssist>Brake Assist: Included</brakeAssist>
